server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  main:
    allow-circular-references: true
  flyway:
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
JWT_SECRET: ${JWT_SECRET}
JWT_EXPIRATION_TIME: 86400000
JWT_REFRESH_EXPIRATION_TIME: 604800000
