export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REFRESH_REGISTER = 'REFRESH_REGISTER';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REFRESH_LOGIN = 'REFRESH_LOGIN';

export const SHOW_TOAST = 'SHOW_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'